# Generated by Django 2.0.8 on 2018-10-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_tag_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileset',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
