# Generated by Django 2.0.8 on 2018-10-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0006_auto_20181010_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenote',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='imagenote',
            name='azimuth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trackfeature',
            name='lengthm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Track length in metres'),
        ),
    ]
